### ISSUE TITLE
ArgumentError - invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by bsodmike** [schacon/showoff#157]
Here's the error:

``` bash
inatra::Base#options is deprecated and will be removed, use #settings instead.
Sinatra::Base#options is deprecated and will be removed, use #settings instead.
Sinatra::Base#options is deprecated and will be removed, use #settings instead.
ArgumentError - invalid byte sequence in UTF-8:
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/showoff-0.7.0/lib/showoff.rb:122:in `process_markdown'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/showoff-0.7.0/lib/showoff.rb:283:in `block (2 levels) in get_slides_html'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/showoff-0.7.0/lib/showoff.rb:281:in `each'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/showoff-0.7.0/lib/showoff.rb:281:in `block in get_slides_html'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/showoff-0.7.0/lib/showoff.rb:272:in `each'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/showoff-0.7.0/lib/showoff.rb:272:in `get_slides_html'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/showoff-0.7.0/lib/showoff.rb:374:in `slides'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/showoff-0.7.0/lib/showoff.rb:487:in `block in <class:ShowOff>'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.2/lib/sinatra/base.rb:1212:in `call'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.2/lib/sinatra/base.rb:1212:in `block in compile!'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.2/lib/sinatra/base.rb:785:in `[]'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.2/lib/sinatra/base.rb:785:in `block (3 levels) in route!'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.2/lib/sinatra/base.rb:801:in `route_eval'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.2/lib/sinatra/base.rb:785:in `block (2 levels) in route!'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.2/lib/sinatra/base.rb:822:in `block in process_route'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.2/lib/sinatra/base.rb:820:in `catch'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.2/lib/sinatra/base.rb:820:in `process_route'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.2/lib/sinatra/base.rb:784:in `block in route!'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.2/lib/sinatra/base.rb:783:in `each'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.2/lib/sinatra/base.rb:783:in `route!'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.2/lib/sinatra/base.rb:886:in `dispatch!'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.2/lib/sinatra/base.rb:719:in `block in call!'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.2/lib/sinatra/base.rb:871:in `block in invoke'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.2/lib/sinatra/base.rb:871:in `catch'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.2/lib/sinatra/base.rb:871:in `invoke'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.2/lib/sinatra/base.rb:719:in `call!'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.2/lib/sinatra/base.rb:705:in `call'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in `call'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/rack-protection-1.2.0/lib/rack/protection/path_traversal.rb:16:in `call'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/rack-protection-1.2.0/lib/rack/protection/json_csrf.rb:17:in `call'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/rack-protection-1.2.0/lib/rack/protection/base.rb:47:in `call'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in `call'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/rack-1.4.0/lib/rack/logger.rb:15:in `call'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/rack-1.4.0/lib/rack/head.rb:9:in `call'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/rack-1.4.0/lib/rack/methodoverride.rb:21:in `call'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.2/lib/sinatra/showexceptions.rb:21:in `call'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.2/lib/sinatra/base.rb:1334:in `block in call'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.2/lib/sinatra/base.rb:1416:in `synchronize'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/sinatra-1.3.2/lib/sinatra/base.rb:1334:in `call'
    /Users/mdesilva/.rvm/gems/ruby-1.9.2-p290/gems/rack-1.4.0/lib/rack/handler/webrick.rb:59:in `service'
    /Users/mdesilva/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/webrick/httpserver.rb:111:in `service'
    /Users/mdesilva/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/webrick/httpserver.rb:70:in `run'
    /Users/mdesilva/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/webrick/server.rb:183:in `block in start_thread'
```

**Comment by bsodmike** [comment]
Fix provided above.
