### ISSUE TITLE
Errno::EPIPE - Broken pipe:

### ISSUE THREAD

**Issue by cmoulliard** [schacon/showoff#187]
Hi,

I hav started 'showoff serve' and when I click on the "Generate PDF" button, I get this error message -->

http://localhost:9090/ -> /slides
/Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.1.4/lib/bundler/rubygems_integration.rb:147:in `block in replace_gem': wkhtmltopdf is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
    from /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/bin/wkhtmltopdf:18:in`<main>'
    from /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in`<main>'
Errno::EPIPE - Broken pipe:
    /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/gems/pdfkit-0.5.2/lib/pdfkit/pdfkit.rb:65:in `write'
    /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/gems/pdfkit-0.5.2/lib/pdfkit/pdfkit.rb:65:in`puts'
    /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/gems/pdfkit-0.5.2/lib/pdfkit/pdfkit.rb:65:in `block in to_pdf'
    /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/gems/pdfkit-0.5.2/lib/pdfkit/pdfkit.rb:64:in`popen'
    /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/gems/pdfkit-0.5.2/lib/pdfkit/pdfkit.rb:64:in `to_pdf'
    /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/gems/pdfkit-0.5.2/lib/pdfkit/pdfkit.rb:76:in`to_file'
    /Users/chmoulli/repositories/GitHub/showoff/lib/showoff.rb:497:in `pdf'
    /Users/chmoulli/repositories/GitHub/showoff/lib/showoff.rb:599:in`block in class:ShowOff'
    /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/gems/sinatra-1.3.2/lib/sinatra/base.rb:1212:in `call'
    /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/gems/sinatra-1.3.2/lib/sinatra/base.rb:1212:in`block in compile!'
    /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/gems/sinatra-1.3.2/lib/sinatra/base.rb:785:in `[]'
    /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/gems/sinatra-1.3.2/lib/sinatra/base.rb:785:in`block (3 levels) in route!'
    /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/gems/sinatra-1.3.2/lib/sinatra/base.rb:801:in `route_eval'
    /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/gems/sinatra-1.3.2/lib/sinatra/base.rb:785:in`block (2 levels) in route!'
    /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/gems/sinatra-1.3.2/lib/sinatra/base.rb:822:in `block in process_route'
    /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/gems/sinatra-1.3.2/lib/sinatra/base.rb:820:in`catch'
    /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/gems/sinatra-1.3.2/lib/sinatra/base.rb:820:in `process_route'
    /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/gems/sinatra-1.3.2/lib/sinatra/base.rb:784:in`block in route!'
    /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/gems/sinatra-1.3.2/lib/sinatra/base.rb:783:in `each'
    /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/gems/sinatra-1.3.2/lib/sinatra/base.rb:783:in`route!'
    /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/gems/sinatra-1.3.2/lib/sinatra/base.rb:886:in `dispatch!'
    /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/gems/sinatra-1.3.2/lib/sinatra/base.rb:719:in`block in call!'
    /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/gems/sinatra-1.3.2/lib/sinatra/base.rb:871:in `block in invoke'
    /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/gems/sinatra-1.3.2/lib/sinatra/base.rb:871:in`catch'
    /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/gems/sinatra-1.3.2/lib/sinatra/base.rb:871:in `invoke'
    /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/gems/sinatra-1.3.2/lib/sinatra/base.rb:719:in`call!'
    /Users/chmoulli/.rvm/gems/ruby-1.9.3-p194/gems/sinatra-1.3.2/lib/sinatra/base.rb:705:in `call'

Regards,

Charles

**Comment by cmoulliard** [comment]
Problem solved after installing khtmltopdf and adding it in the path
